name: CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      runner_scale_set:
        description: Runner Scale Set
        required: true
        default: 'arc-primary'
        type: choice
        options:
          - arc-primary
          - arc-secondary

jobs:
  call_workflow_build:
    name: Node Build
    uses: devsecops-lab-ciandt/devsecops-workflows/.github/workflows/build-node.yml@main

  call_workflow_test:
    name: Node Test
    needs: call_workflow_build
    uses: devsecops-lab-ciandt/devsecops-workflows/.github/workflows/test-node.yml@main

  call_workflow_deploy:
    name: Node Deploy
    needs: call_workflow_test
    uses: devsecops-lab-ciandt/devsecops-workflows/.github/workflows/deploy-node.yml@main
